### ISSUE TITLE
csv output

### ISSUE THREAD

**Issue by magwaer-dev** [Moffi-bit/Amazon-Scraper#1]
hello, I really love your amazon scraper. Its great! But can you teach me how to output the information into a csv file?
I see you put under this command : title,price,rating,reviews,availability,url. But it seems like it is not working when i put it in the command line. The rest of commands you have works, the csv doesnt, or i dont use it correctly. Can you help me please?

**Comment by Moffi-bit** [comment]
Hello Magwear, 

I am glad that you're enjoying the scraper I created. I am going to be making modifications to the code today to make the scraper more user friendly (e.g allowing the user to choose what csv they want the data to go to). Currently the output will go to a csv named "out". 

The writeToCSV function of the Item class expects a File object. Currently, the code in the program that is responsible for writing the information to the CSV is in the outputData function. You can choose which csv the data goes to by changing "out.csv" to "[your_csv_name].csv". I hope this answers your question.

If you have any additional questions please reach out again!

Happy Scraping!

Moffi-bit

**Comment by magwaer-dev** [comment]
Hello again. Thanks for your detailed response ☺️. I'm glad that you will update the scraper soon, can't wait to try it!
I'm currently a student at a programming university, and I've got on my head a scraping theme. 
I have found your code and tried to make it to be able to process natural language. For example if I input the following text in the command line "scrape xbox games with lowest price of 200 and highest price of 400, for 100 items" it automatically will trigger your command : py scrape.py -i Xbox -l 200 -u 400 -i 100. I've heard that there is a library called spacy which process natural language and activates "coded" hard read commands, or even use chat gpt for it. Do you know how to do this? Or maybe do you want to implement this in the future? Thank you!

**Comment by Moffi-bit** [comment]
Haven't looked into adding the functionality to process natural language, but it definitely seems interesting. I may look into it and see if it's something worth adding to this project. Very cool idea.

**Comment by Moffi-bit** [comment]
Released the updated code. Please let me know how it is and any bugs you may encounter. Star the repo if you enjoy using the scraper!
